function retBox = ConvertBox8dToBox4d( bbox_eightPixel )
    retBox = [min(bbox_eightPixel(2,:)), ...
              min(bbox_eightPixel(1,:)), ...
              max(bbox_eightPixel(2,:)) - min(bbox_eightPixel(2,:)) + 1, ...
              max(bbox_eightPixel(1,:)) - min(bbox_eightPixel(1,:)) + 1];
end

